version: 2
jobs:
  deploy-job:
    docker:
      - image: circleci/php:7.3.8
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "ad:bd:6e:90:c2:24:69:00:4f:8f:7e:93:a1:9b:57:9a"
      - run: echo "User matsu" >> $HOME/.ssh/config
      - run: echo "ForwardAgent yes" >> $HOME/.ssh/config
      - run: ssh-keyscan blog.teraren.com >> ~/.ssh/known_hosts
      - run: curl -sS https://getcomposer.org/installer | php
      - run: php composer.phar install
      - run: php vendor/bin/dep deploy test
workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy-job:
          filters:
            branches:
              only: master

