# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  # deployer
  deploy-job:
    docker:
      - image: centos:7
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "ad:bd:6e:90:c2:24:69:00:4f:8f:7e:93:a1:9b:57"
      - run: echo "User matsubo" >> $HOME/.ssh/config
      - run: echo "ForwardAgent yes" >> $HOME/.ssh/config
      - run: yum -y install php-pear php-devel
      - run: php vendor/bin/dep deploy test
workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy-job:
          filters:
            branches:
              only: master

